services:
  nginx:
    image: nginx:alpine
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - laravel
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - pgcontent:/var/www/html/storage
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: "uireh34t34"
      POSTGRES_DB: vblog
      POSTGRES_USER: vblog_adm
      POSTGRES_PASSWORD: "uireh34t34"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
  pgcontent: