server {
    listen 80;
    server_name dev.vblog.local;

    location / {
        proxy_pass         http://dev_panel:80;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
